"use client";
import { HardHat, MapPin, Radio } from "lucide-react";
import type { HelmetData } from "@/hooks/useHelmetData";
import { findCheckpoint, getWorkerCoveragePosition, CHECKPOINTS } from "@/lib/mineMap/checkpoints";

export default function HelmetList({ helmets, selectedId, onSelect, onAlert }: { helmets: HelmetData[]; selectedId:string|null; onSelect:(id:string)=>void; onAlert:(helmet:HelmetData)=>void; }) {
  if (!helmets.length) return <div className="rounded-xl border border-slate-800 bg-[#071118] p-8 text-center text-xs text-slate-500">No helmet records available in Firebase.</div>;
  return <div className="space-y-2">{helmets.map(h=>{const cp=findCheckpoint(h.checkpoint.where);const coverage=cp?getWorkerCoveragePosition(cp.id,CHECKPOINTS):null;const online=h.wifi_rssi!==null||h.uptime!==null||h.temperature!==null;return <div key={h.helmetId} role="button" tabIndex={0} onClick={()=>onSelect(h.helmetId)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")onSelect(h.helmetId)}} className={`w-full rounded-xl border p-3 text-left transition ${selectedId===h.helmetId?"border-red-500/60 bg-red-500/10":"border-slate-800 bg-[#071118] hover:border-slate-700"}`}><div className="flex items-center gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-900"><HardHat className="h-5 w-5 text-slate-300"/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold">{h.helmetId.replace("_","-").toUpperCase()}</span><span className={`text-[9px] font-semibold ${online?"text-emerald-400":"text-red-400"}`}>● {online?"ACTIVE":"OFFLINE"}</span></div><p className="mt-1 text-[10px] text-slate-500">{h.workerName||h.workerId||"Worker: N/A"}</p></div><button type="button" onClick={e=>{e.stopPropagation();onAlert(h)}} className="rounded-md border border-red-500/30 bg-red-500/10 px-2 py-1 text-[9px] text-red-300 hover:bg-red-500/20">ALERT</button></div><div className="mt-3 grid grid-cols-2 gap-2 text-[9px]"><div className="text-slate-500"><Radio className="mr-1 inline h-3 w-3"/>{h.wifi_rssi!==null?`${h.wifi_rssi} dBm`:"Signal N/A"}</div><div className="text-slate-500"><MapPin className="mr-1 inline h-3 w-3"/>{cp?.name||h.checkpoint.where||"Checkpoint N/A"}</div></div>{coverage&&<p className="mt-2 text-[9px] text-slate-600">Coverage: {coverage.from.name}{coverage.to?` → ${coverage.to.name}`:" (final)"}</p>}</div>})}</div>;
}
