"use client";
import Image from "next/image";
import { MapPin } from "lucide-react";
import type { HelmetData } from "@/hooks/useHelmetData";
import { CHECKPOINTS, findCheckpoint, getWorkerCoveragePosition } from "@/lib/mineMap/checkpoints";

export default function MineMap({ helmets, selectedId, onSelectHelmet }: { helmets:HelmetData[]; selectedId:string|null; onSelectHelmet:(id:string)=>void; }) {
  return <div className="overflow-hidden rounded-xl border border-slate-800 bg-black"><div className="relative aspect-[16/9] w-full"><Image src="/mine-tunnel-map.jpeg" alt="Mine tunnel network" fill priority className="object-contain"/><div className="absolute inset-0">{CHECKPOINTS.map(cp=><button key={cp.id} type="button" title={cp.name} className="absolute -translate-x-1/2 -translate-y-1/2" style={{left:`${cp.x}%`,top:`${cp.y}%`}}><span className="flex h-5 w-5 items-center justify-center rounded-full border-2 border-blue-300 bg-blue-600/80 text-[7px] font-bold text-white">{cp.id.slice(-2)}</span><span className="mt-1 block whitespace-nowrap rounded bg-black/70 px-1 text-[7px] text-blue-200">{cp.name}</span></button>)}{helmets.map(h=>{const cp=findCheckpoint(h.checkpoint.where);const pos=cp?getWorkerCoveragePosition(cp.id):null;if(!pos)return null;const selected=h.helmetId===selectedId;return <button key={h.helmetId} type="button" onClick={()=>onSelectHelmet(h.helmetId)} title={`${h.helmetId} • ${h.checkpoint.where||"Checkpoint N/A"}`} className="absolute -translate-x-1/2 -translate-y-1/2" style={{left:`${pos.x}%`,top:`${pos.y}%`}}><span className={`flex h-8 w-8 items-center justify-center rounded-full border-2 ${selected?"border-white bg-red-500":"border-red-300 bg-red-600/80"} shadow-lg`}><MapPin className="h-4 w-4 text-white"/></span><span className="mt-1 block whitespace-nowrap rounded bg-black/80 px-1.5 py-0.5 text-[8px] font-semibold text-white">{h.helmetId.replace("_","-").toUpperCase()}</span></button>})}</div></div><div className="flex flex-wrap gap-4 border-t border-slate-800 bg-[#071118] px-4 py-2 text-[9px] text-slate-400"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-blue-500"/>Checkpoint</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-red-500"/>Worker coverage</span><span>RFID: last checkpoint crossed</span></div></div>;
}
